# Generated by Django 2.2.2 on 2019-06-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=11)),
                ('shift', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('I', 'Integral')], default='I', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=11)),
                ('speciality', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=11)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher'), ('O', 'Outro')], default='H', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
