# Generated by Django 2.2.2 on 2019-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190630_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
