# Generated by Django 2.2.7 on 2019-11-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20191125_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='hour',
            field=models.TimeField(),
        ),
    ]
